name: shelf_appengine
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: shelf appengine fun
homepage: https://github.com/dart-lang/shelf_appengine
dependencies:
  appengine:
    git:
      ref: v0.1
      url: https://github.com/dart-lang/appengine
  shelf: any
