name: shelf_appengine
version: 0.1.1-dev
author: Dart Team <misc@dartlang.org>
description: shelf appengine fun
homepage: https://github.com/dart-lang/shelf_appengine
dependencies:
  appengine:
    git:
      ref: v0.1
      url: https://github.com/dart-lang/appengine
  mime: '>=0.9.0 <0.10.0'
  shelf: '>=0.5.0 <0.6.0'
