author: Dart Team <misc@dartlang.org>
description: shelf appengine fun
homepage: https://github.com/dart-lang/shelf_appengine
name: shelf_appengine
version: 0.3.0
dependencies: 
  appengine: '>=0.2.1 <0.3.0'
  mime: '>=0.9.0 <0.10.0'
  shelf: '>=0.6.0 <0.7.0'
dependency_overrides: 
dev_dependencies: 
environment: 
  sdk: '>=1.0.0 <2.0.0'
